Increase timeout and memory
GoogleCloudPlatform/jobs-demos pull request #29
Opened 2022-10-09 18:21 UTC by jecfish

2022-10-09 18:24 UTC, jecfish commented
@steren PTAL

2022-10-09 21:51 UTC, steren requested changes

2022-10-09 21:51 UTC, steren commented on user-journeys/replay_on_gcp.sh
> +  --task-timeout 3600 \
I'm nor sure we want to default to 1h timeout. It's probably better to still enforce a reasonable timeout. The default is 10minute, I'm not sure we should expect user journeys that takemore than 10min to complete.

I suggest removing this line

2022-10-10 16:00 UTC, steren approved these changes

2022-10-10 18:10 UTC, jecfish commented
@steren apparently I cannot merge this request as I am not authorized. Pls help to merge it.

2022-10-10 18:59 UTC, merged